moklick/frontend-stuff

- README.md
Another great resource for HTML5 video/audio to add to the others.
> add Plyr to video resources

- README.md
SUI components are all released individually which might be useful to developers who are just looking for a single solution. 
The transition component is particularly useful for standalone CSS animations that transition DOM elements in and out of view.  Check [out our examples](http://semantic-ui.com/modules/transition.html#/examples)
> Add SUI Animation Component

- README.md
A handpicked collection of beautiful colour gradients for design and code.
> add uiGradients

- README.md
As suggested in https://github.com/moklick/frontend-stuff/pull/22
Added countup.js to UI Elements
> Added countUp.js to UI Elements

- README.md
Another cool stuff for CSS animations.
> Add animate.css to Animations section

- README.md
Hey, I think it's worth noting DataTables plugin for jQuery.
> Add DataTables to Tables section

- README.md
I have added the ScrollMagic library that makes it easy to trigger effects and animations in both scrolling directions.
> Added a scrolling library (ScrollMagic)

- README.md
Added messenger.js under UI Elements. Its a nice message, notification plugin. Feel like to share  :)
> Added Messenger.js under UI Elements.

- README.md
Requesting the addition of Caramel.
(github.com/kurisubrooks/caramel)
> Added Caramel

- README.md
Adding Plumin.js and Typeplate under 'Text' category
> 'Text' additions

- README.md
Added Kartograph, mapsicon, and colorbrewer
> Some 'Map' and related additions

- README.md
Adding two new items:
Hover.css is a collection of hover effects to be applied to links, buttons, logos...
Sortable.js is a JavaScript library to drag-and-drop lists.
> add hover.css and sortable.js

- README.md
Flaticon is AFAIK the biggest repository of free icons, and it includes a search engine
and all the icons are available in lots of formats. I use it all the time.
> Add another big icon repository

- README.md
Hello! As you suggested in #2766, I created new section, `Module loaders`, and added RequireJS into it.
> Add RequireJS to new Module loaders section

- README.md
Hello, I would like to propose an addition to Text section - slabText. It brings great styling for your headlines!
> Add slabText to Text section

- README.md
Added Famo.us to UI Frameworks section
> Added Famo.us

- README.md
Parsley is an ultimate form validation library. Very easy to start, really no JavaScript code needed (unless you have complex form with step-by-step validation). I have added a new section for it.
> Create Form validation section, add Parsley

- README.md
Some other useful libraries. (hopefully)
> Added Chart.JS, Modernizr, Typeahead, and Vexflow

- README.md
http://sapegin.github.io/social-likes/
> Add Social Likes

- README.md
Vex has a good documentation, multiple themes out of the box and a clean UI.
http://github.hubspot.com/vex/
> Added vex modal dialogs

- README.md
ECharts is an open source (MIT License) comprehensive charting library and interactive data visualization tool used by Baidu
> Add ECharts to charts section

- README.md
I suggest to add https://icomoon.io/, great website to generate fonts with icons to be used in Ionic (or in many other ways)
> Add Icomoon.io

- README.md
Added snapsvg.js and vivus.js - two great libs for SVG animations.
> Added libs in Animations for animating SVG's

- README.md
Simple, robust, extensible JavaScript charting library built using d3 designed to help developers embed, build charts in less than couple of minutes. Really quick to get up, running, and using effectively.
> Adding uvCharts

- README.md
Metro UI CSS is a front-end UI framework for developing Windows Metro style website.
It contains many easy-to-use UI components and have a clear documentation.
https://metroui.org.ua/
> Add Metro UI

- README.md
lazysizes is my favourite lazyloader for responsive images with picture or srcset. works without dependencies and configuration.
works also with iframes, scripts and more.
> add lazysizes to lazyload section

- README.md
I leave it up to you whether you want to have dat.GUI in there.
> added tone.js, pixi.js, gui.DAT

- README.md
> Add HTML-Starterkit to UI Frameworks

- README.md
Added **mini.css** as discussed in #2830
> Add mini.css

- README.md
https://github.com/vitalets/bro-fs
Thanks in advance!
> Add bro-fs library

- README.md
A simple JavaScript framework for building ambitious UIs
> Added DisplayJS

- README.md
> Simple dependency free ES6 library to produce small on-screen nudges
It simply allows you to display a small unobtrusive on-screen prompt for a few moments, very useful for saving notifications, new friend requests, updated messages etc.
> Adding nudge
